title: Nikita Titorenko CV
description:  Nikita Titorenko CV
url: https://thetitorenko.github.io/thetitorenko/
baseurl: ''
theme_skin: blue

sass:
  sass_dir: _sass
  style: compressed

plugins:
    - jekyll-minifier

exclude:
  - docker-compose.yml
